# Generated by Django 5.2.11 on 2026-02-25 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=2000, verbose_name="link")),
                (
                    "short_link",
                    models.CharField(max_length=2000, verbose_name="short link"),
                ),
                (
                    "usage",
                    models.PositiveIntegerField(
                        default=0, verbose_name="number of usage"
                    ),
                ),
                (
                    "duration",
                    models.BigIntegerField(default=86400, verbose_name="duration"),
                ),
                (
                    "is_expired",
                    models.BooleanField(default=False, verbose_name="expired"),
                ),
                (
                    "users",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
