# Generated by Django 5.2.11 on 2026-02-25 19:21

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=13, unique=True, verbose_name="phone number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="is active"),
                ),
                (
                    "verification_code",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        null=True,
                        verbose_name="verification code",
                    ),
                ),
                (
                    "verification_expiry",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="verification code expiry"
                    ),
                ),
                ("date_joined", models.DateTimeField(verbose_name="date joined")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("is_staff", models.BooleanField(default=False, verbose_name="staff")),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="superuser"),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
